### ISSUE TITLE
Could this be upgraded to gcc-10?

### ISSUE THREAD

**Issue by rhalbersma** [jwakely/pkg-gcc-latest#1]
The latest available snapshot is: https://gcc.gnu.org/pub/gcc/snapshots/LATEST-10/

It would be nice if this repo always pointed to the tip-of-trunk of the developmant branch, making it easy to track gcc-latest support on Travis CI.

**Comment by jwakely** [comment]
Yes, I've been planning to update it. It's not been a priority because trunk is still very close to the 9.1.0 release, so the benefit of using trunk is much less than near the end of a release cycle.

**Comment by jwakely** [comment]
`gcc-latest_10.0.0-20190602svn271848.deb` is available now.
