### ISSUE TITLE
put builds into Github Releases?

### ISSUE THREAD

**Issue by niXman** [jwakely/pkg-gcc-latest#10]
hi,

my question is, why not upload release builds into Github Releases?: https://github.com/jwakely/pkg-gcc-latest/releases
then all releases will be in one place, and all Github users know that releases are located there.

best!

**Comment by niXman** [comment]
moreover, it would be great if you will provide a VirusTotal report for the all package.
like there: https://github.com/niXman/mingw-builds-binaries/releases

**Comment by jwakely** [comment]
I manually added the latest one as https://github.com/jwakely/pkg-gcc-latest/releases/tag/20230212 but I would need to automate that using Actions, which I don't have time for now.

The VirusTotal report just keeps running forever: https://www.virustotal.com/gui/url-analysis/u-2a2bc96d9c986b1cae47a9975dd41bb26381c04b316dd9dbe0b38b8315ead9d1-1676458108

That's even though I already generated a report for the identical file at a different URL: https://www.virustotal.com/gui/url/99434bcd41e171eb150ffce07198bb126f40abb6999ee9c67c64aab14e6035ec

I don't plan to sign up for that service to be able to automate such checks.

**Comment by jwakely** [comment]
> then all releases will be in one place

But they won't, only the `.deb` files. The RPMs will still be at https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/

There is no way I'm uploading all the RPMs to Github Releases, that's just a waste of time, bandwidth, and disk space.

**Comment by niXman** [comment]
> I would need to automate that using Actions, which I don't have time for now.

JFYI: https://github.com/actions/upload-artifact

> The VirusTotal report just keeps running forever

hmm.. very strange...

> There is no way I'm uploading all the RPMs to Github Releases, that's just a waste of time, bandwidth, and disk space.

got it.



thanks, closed!
