### ISSUE TITLE
GCC 14

### ISSUE THREAD

**Issue by real-or-random** [jwakely/pkg-gcc-latest#14]
Thanks for providing these builds!

 The development branch is now GCC 14. Are you planning to update this?

In general, is there a rule of thumb of how often a new build is made available? Every 2-3 months? No need to promise anything, I just would like to get an idea of how often this happened in the past. :)

**Comment by jwakely** [comment]
There's a weekly snapshot and I usually build every snapshot. I just haven't done it since gcc 13 branched from trunk.

**Comment by jwakely** [comment]
The new builds are available now.

**Comment by jwakely** [comment]
Ugh, I didn't even look at which repo the linked issue was from, and so didn't realise this would be benefitting buttcoin. I might "forget" to do next week's snapshot.
