### ISSUE TITLE
Broken manpages

### ISSUE THREAD

**Issue by davidmalcolm** [jwakely/pkg-gcc-latest#19]
All of the manpages seem to be 10 bytes, simply containing the string "timestamp".

The log has e.g.:

```
perl ../../gcc/../contrib/texi2pod.pl ../../gcc/doc/invoke.texi > gcc.pod
/bin/sh: line 1: perl: command not found
make[2]: [Makefile:3729: gcc.pod] Error 127 (ignored)
echo timestamp > doc/gcc.1
```

I tried adding:

BuildRequires: perl

in my own fork, and it fixed the manpages.

**Comment by jwakely** [comment]
I don't think I've ever tried to look at the man pages in the package! Thanks for the fix.

**Comment by jwakely** [comment]
A new build is ... building:
https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/build/8173545/
