### ISSUE TITLE
Git migration

### ISSUE THREAD

**Issue by cpplearner** [jwakely/pkg-gcc-latest#2]
The latest snapshot ( https://gcc.gnu.org/pub/gcc/snapshots/10-20200119/ ) now uses git instead of svn. Some changes may be needed to deal with this.

At a first glance, the following places seem to be affected:

`/trunk revision/` => `/master revision/`; might also need to shorten revision hash:
https://github.com/jwakely/pkg-gcc-latest/blob/40954ea9df22758bd1204e50bc133c6d65fb35b7/build.sh#L32

svn => git in three places:
https://github.com/jwakely/pkg-gcc-latest/blob/40954ea9df22758bd1204e50bc133c6d65fb35b7/build.sh#L46
https://github.com/jwakely/pkg-gcc-latest/blob/40954ea9df22758bd1204e50bc133c6d65fb35b7/build.sh#L72
https://github.com/jwakely/pkg-gcc-latest/blob/40954ea9df22758bd1204e50bc133c6d65fb35b7/build.sh#L75

Web page (also need to update [Makefile](https://github.com/jwakely/pkg-gcc-latest/blob/0ff6f35b388cac63ab9b94ef7407f318c504574b/Makefile)):
https://github.com/jwakely/pkg-gcc-latest/blob/0ff6f35b388cac63ab9b94ef7407f318c504574b/index.md#L72-L75
https://github.com/jwakely/pkg-gcc-latest/blob/0ff6f35b388cac63ab9b94ef7407f318c504574b/index.md#L93

**Comment by jwakely** [comment]
Yeah I'll need to change those, so thanks for finding them. I haven't been building the snapshots for few weeks anyway, not only related to the git migration.

**Comment by jwakely** [comment]
Should be all working now, with new deb packages online - thanks!
