### ISSUE TITLE
no new rpms in a while?

### ISSUE THREAD

**Issue by sweettea** [jwakely/pkg-gcc-latest#3]
Greetings;

I was trying to install off copr today, https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/, but it seems there hasn't been a rebuild there in quite a while... is there a blocking issue that I can't find offhand preventing new builds? Would love to help if possible and needed.

Many thanks!

**Comment by jwakely** [comment]
Something failed last time I tried a build, but I didn't look into it. I'll try it again.

**Comment by jwakely** [comment]
Trying to upload the SRPM to COPR fails with:

> Request is not in JSON format, there is probably a bug in the API code.

**Comment by jwakely** [comment]
Looks like https://pagure.io/copr/copr/issue/1228

**Comment by jwakely** [comment]
This was resolved a while ago.
