### ISSUE TITLE
fortran

### ISSUE THREAD

**Issue by dschwoerer** [jwakely/pkg-gcc-latest#4]
I looked at this a while ago, but due to the lack of fortran, I had to compile from source :-(

It would be lovely if you could enable more languages to make the package more useful :-)
I am currently mostly interested in fortran, but if it is not to much effort, having all the languages from the main gcc package support would be ideal, I guess.

Edit: I am referring to the copr builds, not sure what other artifacts are produced ...

**Comment by jwakely** [comment]
Actually, as it says at https://gcc.gnu.org/wiki/GFortranBinaries#Linux you can get nightly snapshots from gfortran.com so I'm not going to bother enabling Fortran for my builds. My interest is in making new C++ features available to people who want to try them. For other languages, the maintainers of those parts of GCC can do it.
