### ISSUE TITLE
installing gcc-latest complains about missing TSAN and ASAN libs

### ISSUE THREAD

**Issue by niekbouman** [jwakely/pkg-gcc-latest#5]
Dear @jwakely ,

Thank you for making gcc-latest available to, in my case, Fedora users.
When trying to install gcc-latest, I run into the following issue: (problem appears in a Fedora 35 Toolbox as well as in a Fedora 36 Toolbox), 
```
Error: 
 Problem: conflicting requests
  - nothing provides libasan.so.8()(64bit) needed by gcc-latest-12.0.0-1.20211114git3057f1ab7375.fc36.x86_64
  - nothing provides libtsan.so.2()(64bit) needed by gcc-latest-12.0.0-1.20211114git3057f1ab7375.fc36.x86_64
  - nothing provides libasan.so.8()(64bit) needed by gcc-latest-12.0.0-1.20211121gitda17c304e22b.fc36.x86_64
  - nothing provides libtsan.so.2()(64bit) needed by gcc-latest-12.0.0-1.20211121gitda17c304e22b.fc36.x86_64
```
Any idea how to fix this?

**Comment by jwakely** [comment]
I see this on Fedora 34 too, but I haven't had time to look into it yet.

**Comment by terjeros** [comment]
The _requires_exclude regex seems to be a bit off, try something like this:
```
diff --git a/gcc-latest.spec.m4 b/gcc-latest.spec.m4
index db81ded..36e13a3 100644
--- a/gcc-latest.spec.m4
+++ b/gcc-latest.spec.m4
@@ -4,7 +4,7 @@
 # or any files in the application's data directory for provides
 %global __provides_exclude_from ^%{install_prefix}/%{_lib}/
 # Do not generate auto-requires for symlinks to libs in this package.
-%global __requires_exclude ^lib(c[cp]1plugin|lto_plugin|atomic|cc1|gomp|itm|quadmath|(a|l|t|ub)san).so.?\\(\\)\\(.*\\)$
+%global __requires_exclude ^lib(c[cp]1plugin|lto_plugin|atomic|cc1|gomp|itm|quadmath|(a|l|t|ub)san)\.so\..?\\(\\)\\(.*\\)$

 # Hardening slows the compiler way too much.
 %undefine _hardened_build
```

A sole .? after .so will just match the . while in fact what's after .so is a . and then a number.

Note: fixed pattern above will only work until some lib gets soname larger than 9.

**Comment by jwakely** [comment]
I'm testing this:
`%global __requires_exclude ^lib(c[cp]1plugin|lto_plugin|atomic|cc1|gomp|itm|quadmath|(a|l|t|ub)san)\\.so(\\.[[:digit:]]+)*\\(\\)\\(.*\\)$`

But maybe it should be simply `\\.so*` instead.

**Comment by jwakely** [comment]
There's a new build running with the change: https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/build/2990979/

**Comment by niekbouman** [comment]
That build unfortunately failed.
Seems to get stuck here:
```
Checking multilib configuration for libgcc...

[...some lines removed by me...]

checking for suffix of object files... configure: error: in `/builddir/build/BUILD/gcc-12-20211121/objdir/x86_64-pc-linux-gnu/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
make[1]: *** [Makefile:13583: configure-target-libgcc] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jwakely** [comment]
Bah, I tried enabling annobin:

    cc1: fatal error: inaccessible plugin file plugin/annobin.so expanded from short plugin name annobin: No such file or directory

**Comment by jwakely** [comment]
The new [build](https://copr.fedorainfracloud.org/coprs/jwakely/gcc-latest/build/2992818/) succeeded. Thanks for the report and the pointer to the regex bug.

**Comment by niekbouman** [comment]
Installation in Fedora now works! Thanks!!
