### ISSUE TITLE
Segmentation Fault on Ubuntu 22.04

### ISSUE THREAD

**Issue by pkeir** [jwakely/pkg-gcc-latest#7]
I have installed gcc-latest_13.0.0-20221127git4ac789789ea8.deb on Ubuntu 22.04 and find that running "hello world" produces a segmentation fault. If I add the `-static` flag, the error disappears. Further details:

```
$ cat hello.cpp 
#include <iostream>

int main(int argc, char *argv[])
{
  std::cout << "Hello.\n";
  return 0;
}

$ /opt/gcc-latest/bin/g++ hello.cpp 
$ ./a.out 
Segmentation fault (core dumped)
$ /opt/gcc-latest/bin/g++ -static hello.cpp 
$ ./a.out 
Hello.
```

**Comment by pkeir** [comment]
Actually, this is as expected. I just use `export LD_LIBRARY_PATH=/opt/gcc-latest/lib64:$LD_LIBRARY_PATH` as explained on the website, and all is good.

**Comment by jwakely** [comment]
Linking to the new libstdc++.so is definitely required. I'm not sure why it would segfault though. I would expect an error from the dynamic linker. I'll look into it.

**Comment by jwakely** [comment]
This is caused by https://github.com/gcc-mirror/gcc/commit/4e4e3ffd10f53ef71696bc728ab40258751a2df4 which introduces an incompatibility between the old and new libstdc++.so versions. Ideally we'd get a linker error instead of a segfault.
