### ISSUE TITLE
Nothing provides libhwasan.so.0()(64bit) needed by gcc-latest

### ISSUE THREAD

**Issue by Mno-hime** [jwakely/pkg-gcc-latest#8]
Hi, thanks for packaging gcc-latest for Fedora!

I have the following issue when DNF attempts to update `gcc-latest-13.0.0-2.20221204git24b9337d1f1b.fc37.x86_64` to `gcc-latest-13.0.0-2.20221218gitfd69977febf3.fc37.x86_64` on two Fedora 37 systems from your Copr:

```
 Problem: cannot install the best update candidate for package gcc-latest-13.0.0-2.20221204git24b9337d1f1b.fc37.x86_64
  - nothing provides libhwasan.so.0()(64bit) needed by gcc-latest-13.0.0-2.20221218gitfd69977febf3.fc37.x86_64
```

Looking at [Fedora 37 x86-64 build logs](https://download.copr.fedorainfracloud.org/results/jwakely/gcc-latest/fedora-37-x86_64/05154716-gcc-latest/build.log.gz), it seems `libhwasan.so.0` is part of the `gcc-latest` package.

**Comment by Mno-hime** [comment]
FTR not yet fixed in `gcc-latest-13.0.0-2.20230101git4f1314f547f6.fc37.x86_64`:
```
# dnf in gcc-latest
...
Error: 
 Problem: conflicting requests
  - nothing provides libhwasan.so.0()(64bit) needed by gcc-latest-13.0.0-2.20221218gitfd69977febf3.fc37.x86_64
  - nothing provides libhwasan.so.0()(64bit) needed by gcc-latest-13.0.0-2.20230101git4f1314f547f6.fc37.x86_64
```

**Comment by jwakely** [comment]
I forgot to pull the fix locally before building :facepalm:

**Comment by jwakely** [comment]
Rebuildin' ...

**Comment by jwakely** [comment]
... done.

**Comment by Mno-hime** [comment]
Confirmed. Thank you!
